// Generated by CoffeeScript 1.12.7
(function() {
  var app, express, listener, mongo, path, uri, url;

  express = require('express');

  url = require('url');

  path = require('path');

  mongo = require('mongodb').MongoClient;

  app = express();

  uri = 'mongodb://arnaldopxm:' + '130796' + '@ds137197.mlab.com:37197/freecodecamp';

  app.set('view engine', 'pug');

  app.set('views', path.join(__dirname, 'views'));

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.get('/new/*', function(req, res) {
    var dir;
    dir = req.params[0];
    return mongo.connect(uri, function(err, db) {
      var collection;
      if (err) {
        throw err;
      }
      collection = db.collection('uris');
      return collection.count({
        "short": {
          $gte: 0
        }
      }, function(err, count) {
        var obj, sol;
        if (err) {
          throw err;
        }
        sol = {
          url: dir,
          short: count
        };
        obj = {
          query: {
            "url": dir
          },
          update: {
            "short": count
          },
          upsert: true
        };
        return collection.findAndModify(obj, function(err, data) {
          console.log(data);
          if (err) {
            throw err;
          }
        });
      });
    });
  });

  listener = app.listen(50532, function() {
    return console.log('Your app is listening on port ' + listener.address().port);
  });

}).call(this);
